### ISSUE TITLE
Newtonsoft Json dependency

### ISSUE THREAD

**Issue by CarambulaGit** [Dest-69/advanced-popup-system#3]
![image](https://github.com/user-attachments/assets/0cede715-3967-4af5-9758-17d0cf62c548)
Add Newtonsoft Json as a dependency
![image](https://github.com/user-attachments/assets/917c26a3-f898-456d-b340-353be670d05a)

**Comment by Dest-69** [comment]
b6ae4bf9de2852f55dc51328108d474984096c3c
