### ISSUE TITLE
Fix Popup System Editor for white theme of Unity

### ISSUE THREAD

**Issue by CarambulaGit** [Dest-69/advanced-popup-system#4]
![image](https://github.com/user-attachments/assets/62dd2e2e-9925-41b2-a8f3-d630672c9884)
![image](https://github.com/user-attachments/assets/b52a43b2-b43b-4e4c-b0da-4a62ef738bc2)

**Comment by Dest-69** [comment]
09bff5d3a9cb802972d157d1396915ac96a2f31e
Also fixed this one
![image](https://github.com/user-attachments/assets/df61115d-1632-489f-a920-ebc5f0d9cf20)

To this
![image](https://github.com/user-attachments/assets/9473b31a-a80a-444e-b314-4a8a6e9df7cc)
