### ISSUE TITLE
Popup is opened, but invisible because of alpha in canvas group

### ISSUE THREAD

**Issue by CarambulaGit** [Dest-69/advanced-popup-system#6]
After closing popup, if you try to open it with correct timing, you can achieve state where popup is opened, but invisible because of alpha param in canvas group
https://github.com/user-attachments/assets/8b81b7bd-8f0b-492c-a2ad-3b692ede3b00

**Comment by Dest-69** [comment]
Thanks @CarambulaGit
a8cda8e22418bdf1fe41789ce6bf91e0b198b998

- Fixed bug with multiple sub/unsubscribe
- Updated codegeneration
0eda1dd3448edfdc4c9583d42c9df2406124975c @Dest-69
